project_id = "brebfhrsxxslqzkkxpvt"

[functions.ai-chat]
verify_jwt = false

[functions.stock-predict]
verify_jwt = false

[functions.news-intelligence]
verify_jwt = false

[functions.wallet-auth]
verify_jwt = false

[functions.portfolio-upload]
verify_jwt = false

[functions.stock-data]
enabled = true
verify_jwt = true
import_map = "./functions/stock-data/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/stock-data/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/stock-data/*.html" ]
